piVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  APP_ENV: "production"
  API_URL: "https://api.example.com"
  CACHE_TTL: "3600"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: production
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/app/*.log
      pos_file /var/log/fluentd-app.log.pos
      tag app.*
      <parse>
        @type json
      </parse>
    </source>

    <match app.**>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      index_name app-logs
      type_name app_log
    </match>
