apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
data:
  DB_PASSWORD: base64encodedpassword
  API_KEY: base64encodedapikey
  JWT_SECRET: base64encodedjwtsecret